// Code generated by Slice Machine. DO NOT EDIT.

import Blog from './Blog';
import Feature from './Feature';
import Hero from './Hero';

export {
	Blog,
	Feature,
	Hero,
};

export const components = {
	blog: Blog,
	feature: Feature,
	hero_block: Hero,
};
